apiVersion: v1
kind: ServiceAccount
metadata:
  name: httproute-webhook
  namespace: httproute-webhook
  labels:
    app.kubernetes.io/name: httproute-webhook
    app.kubernetes.io/component: admission-webhook
